USE MASTER
GO

IF EXISTS(SELECT * FROM SYSDATABASES WHERE NAME = 'FACSQL') 
	DROP DATABASE FACSQL
GO
CREATE DATABASE FACSQL
GO

USE FACSQL
GO

CREATE TABLE MAE_EMIDOCELE(
	NID_EMIDOCELE INT IDENTITY(1,1) NOT NULL,
	NU_EMINUMRUC VARCHAR(11),
	CO_EMICODANE CHAR(4),
	NO_BASTIPBAS VARCHAR(50),
	NO_BASNOMSRV VARCHAR(150),
	NO_BASNOMBAS VARCHAR(50),
	NO_BASUSRBAS VARCHAR(50),
	NO_BASUSRPAS VARCHAR(100),
	--
	FE_REGCREACI DATETIME,
	FE_REGMODIFI DATETIME,
	FL_REGINACTI CHAR(1),
	CONSTRAINT PK_EMIDOCELE_NID_EMIDOCELE PRIMARY KEY (NID_EMIDOCELE)
)
GO

CREATE TABLE TBL_DOCELECAB(
	NID_DOCELECAB INT IDENTITY(1,1) NOT NULL,
	NU_DOCSERSUN VARCHAR(10),
	NU_DOCNUMSUN VARCHAR(10),
	FE_DOCFECEMI DATETIME,
	HO_DOCHOREMI CHAR(8),
	CO_DOCTIPDOC CHAR(2),
	CO_DOCTIPMND CHAR(3),
	FE_DOCFECVEN DATETIME,
	CO_EMITIPDOC CHAR(1),
	NU_EMINUMRUC VARCHAR(11),
	NO_EMINOMCOM VARCHAR(1500),
	NO_EMIRAZSOC VARCHAR(1500),
	NO_EMIDOMDIR VARCHAR(200),
	NO_EMIDOMURB VARCHAR(25),
	NO_EMIDOMPRV VARCHAR(30),
	CO_EMIDOMUBI CHAR(6),
	NO_EMIDOMDEP VARCHAR(30),
	NO_EMIDOMDIS VARCHAR(30),
	CO_EMIDOMPAI CHAR(2),
	FL_VENTAITIN CHAR(1),
	NO_ITNDIRCOM VARCHAR(200),
	NO_ITNURBANI VARCHAR(25),
	NO_ITNPROVIN VARCHAR(30),
	CO_ITNCODUBI CHAR(6),
	NO_ITNDEPART VARCHAR(30),
	NO_ITNDISTRI VARCHAR(30),
	CO_ITNCODPAI CHAR(2),
	FL_VENTAEXPO CHAR(1),
	CO_EXPCODPAI CHAR(2),
	CO_EMICODANE CHAR(4),
	CO_RECTIPDOC CHAR(1),
	NU_RECNUMDOC VARCHAR(15),
	NO_RECRAZSOC VARCHAR(1500),
	CO_REMTIPDOC CHAR(2),
	NU_REMNUMDOC VARCHAR(30),
	FL_REFADIDOC CHAR(1),
	MT_TOTMONIMP DECIMAL(12,2),
	MT_TOTVENEXP DECIMAL(12,2),
	MT_TOTIMPEXP DECIMAL(12,2),
	CO_CODTRIEXP CHAR(4),
	MT_TOTVENINA DECIMAL(12,2),
	MT_TOTIMPINA DECIMAL(12,2),
	CO_CODTRIINA CHAR(4),
	MT_TOTVENEXO DECIMAL(12,2),
	MT_TOTIMPEXO DECIMAL(12,2),
	CO_CODTRIEXO CHAR(4),
	MT_TOTVENGRA DECIMAL(12,2),
	MT_TOTIMPGRA DECIMAL(12,2),
	CO_CODTRIGRA CHAR(4),
	MT_TOTVENGRV DECIMAL(12,2),
	MT_TOTIMPGRV DECIMAL(12,2),
	CO_CODTRIGRV CHAR(4),
	MT_ISCMONBAS DECIMAL(12,2),
	MT_TOTMONISC DECIMAL(12,2),
	FL_CARGODESC VARCHAR(5),
	CO_CODCARDES CHAR(2),
	PO_CARDESPRC DECIMAL(12,5),
	MT_MONCARDES DECIMAL(12,2),
	MT_CARDESBAS DECIMAL(12,2),
	MT_TOTMONDES DECIMAL(12,2),
	MT_TOTMONCAR DECIMAL(12,2),
	MT_TOTIMPORT DECIMAL(12,2),
	MT_TOTVALVEN DECIMAL(12,2),
	MT_TOTPREVEN DECIMAL(12,2),
	CO_ADILEYEND CHAR(4),
	TX_ADIDESLEY VARCHAR(200),
	CO_ADITIPOPE CHAR(4),
	FL_PERCEPCIO CHAR(1),
	NO_PERINCADE VARCHAR(5),
	CO_PERREASON CHAR(2),
	PO_PERPORAPL DECIMAL(12,5),
	MT_PERMONPER DECIMAL(12,2),
	MT_PERBASIMP DECIMAL(12,2),
	FL_ANTICIPOS CHAR(1),
	MT_TOTMONANT DECIMAL(12,2),
	CO_GUIARUBIG CHAR(6),
	NO_GUIARDIRE VARCHAR(200),
	NO_GUIARURBA VARCHAR(25),
	NO_GUIARPROV VARCHAR(30),
	NO_GUIARDEPA VARCHAR(30),
	NO_GUIARDIST VARCHAR(30),
	CO_GUIARPAIS CHAR(2),
	FL_DETRACCIO CHAR(1),
	CO_DTRCODBIE CHAR(3),
	NO_DTRCUEBAN VARCHAR(100),
	MT_DTRMONDTR DECIMAL(12,2),
	PO_DTRPRCDTR DECIMAL(12,5),
	CO_SUNESTENV CHAR(2),
	TX_SUNRESENV VARCHAR(8000),
	FL_SUNDOCXML CHAR(1),
	XM_SUNDOCXML VARCHAR(MAX),
	FL_SUNDOCPDF CHAR(1),
	B6_SUNDOCPDF VARCHAR(MAX),
	FL_SUNDOCCDR CHAR(1),
	B6_SUNDOCCDR VARCHAR(MAX),
	--
	FE_REGCREACI DATETIME,
	FE_REGMODIFI DATETIME,
	FL_REGINACTI CHAR(1),
	CONSTRAINT PK_DOCELECAB_NID_DOCELECAB PRIMARY KEY (NID_DOCELECAB)
)
GO

CREATE TABLE TBL_DOCELEREF(
	NID_DOCELEREF INT IDENTITY(1,1),
	NU_REFDOCORG VARCHAR(40),
	CO_REFTIPDOC CHAR(2),
	NU_REFNUMDOC VARCHAR(30),
	--
	FE_REGCREACI DATETIME,
	FE_REGMODIFI DATETIME,
	FL_REGINACTI CHAR(1),
	NID_DOCELECAB INT,
	CONSTRAINT PK_DOCELEREF_NID_DOCELEREF PRIMARY KEY (NID_DOCELEREF),
	CONSTRAINT FK_DOCELEREF_DOCELECAB_NID_DOCELECAB FOREIGN KEY (NID_DOCELECAB) REFERENCES TBL_DOCELECAB (NID_DOCELECAB)
)
GO

CREATE TABLE TBL_DOCELEDET(
	NID_DOCELEDET INT IDENTITY(1,1),
	NU_DETORDITM VARCHAR(5),
	CO_DETUNDMED VARCHAR(3),
	QT_DETCANITM DECIMAL(12,10),
	CO_DETCODPRO VARCHAR(30),
	CO_DETCOPRSU VARCHAR(8),
	CO_DETCODGS1 VARCHAR(14),
	TX_DETDESITM VARCHAR(500),
	MT_DETVALUNI DECIMAL(12,10),
	MT_DETPREVEN DECIMAL(12,10),
	CO_DETCODPRE CHAR(2),
	MT_DETVALREF DECIMAL(12,10),
	CO_DETCOVARE CHAR(2),
	MT_DETTOTIMP DECIMAL(12,2),
	MT_AFEMONBAS DECIMAL(12,2),
	MT_AFEMONAFE DECIMAL(12,2),
	PO_AFEMONPRC DECIMAL(12,5),
	CO_AFEREASON VARCHAR(2),
	CO_AFECODTRI CHAR(4),
	MT_ISCMONBAS DECIMAL(12,2),
	MT_ISCMONAFE DECIMAL(12,2),
	PO_ISCMONPRC DECIMAL(12,5),
	CO_ISCTIPSIS CHAR(2),
	CO_ISCCODTRI CHAR(4),
	MT_DETVALVEN DECIMAL(12,2),
	NO_DETCARDES VARCHAR(5),
	CO_CARDESREA CHAR(2),
	DE_CARDESFAC DECIMAL(12,5),
	MT_CARDESMON DECIMAL(12,2),
	MT_CDEMONBAS DECIMAL(12,2),
	--
	FE_REGCREACI DATETIME,
	FE_REGMODIFI DATETIME,
	FL_REGINACTI CHAR(1),
	NID_DOCELECAB INT,
	CONSTRAINT PK_DOCELEDET_NID_DOCELEDET PRIMARY KEY (NID_DOCELEDET),
	CONSTRAINT FK_DOCELECAB_DOCELEDET_NID_DOCELECAB FOREIGN KEY (NID_DOCELECAB) REFERENCES TBL_DOCELECAB (NID_DOCELECAB)
)
GO

CREATE TABLE TL_PROFACINT(
	NID_PROFACINT INT IDENTITY(1,1),
	CO_ESTPROINT VARCHAR(30),
	NO_ESTPROINT VARCHAR(100),
	CO_TIPPROFAC VARCHAR(30),
	NO_TIPPROFAC VARCHAR(150),
	--
	FE_REGCREACI DATETIME,
	FE_REGMODIFI DATETIME,
	FL_REGINACTI CHAR(1),
	NID_EMIDOCELE INT
	CONSTRAINT PK_PROMIGINT_NID_PROMIGINT PRIMARY KEY (NID_PROFACINT),
	CONSTRAINT FK_PROMIGINT_NID_EMIDOCELE FOREIGN KEY (NID_EMIDOCELE) REFERENCES MAE_EMIDOCELE(NID_EMIDOCELE)
)
GO

CREATE TABLE MAE_DATGENFAC(
	NID_DATGENFAC INT IDENTITY(1,1),
	NO_NOMMAEFAC VARCHAR(150),
	TX_DESMAEFAC VARCHAR(300),
	NO_CAMPOFAC1 VARCHAR(100),
	NO_CAMPOFAC2 VARCHAR(100),
	NO_CAMPOFAC3 VARCHAR(100),
	NO_CAMPOFAC4 VARCHAR(100),
	NO_CAMPOFAC5 VARCHAR(100),
	NO_CAMPOFAC6 VARCHAR(100),
	--
	FE_REGCREACI DATETIME,
	FE_REGMODIFI DATETIME,
	FL_REGINACTI CHAR(1),
	CONSTRAINT PK_DATGENFAC_NID_DATGENFAC PRIMARY KEY (NID_DATGENFAC),
)

-- INSERCCIÓN DE DATOS
--
INSERT INTO MAE_DATGENFAC(NO_NOMMAEFAC, TX_DESMAEFAC, NO_CAMPOFAC1, NO_CAMPOFAC2, FE_REGCREACI, FL_REGINACTI)
VALUES('TIPPROINT', 'Guarda todos los tipos de procesos de la interface', 'MIG', 'Migración', GETDATE(), '0');
INSERT INTO MAE_DATGENFAC(NO_NOMMAEFAC, TX_DESMAEFAC, NO_CAMPOFAC1, NO_CAMPOFAC2, FE_REGCREACI, FL_REGINACTI)
VALUES('TIPPROINT', 'Guarda todos los tipos de procesos de la interface', 'FAC', 'Facturación', GETDATE(), '0');
--
INSERT INTO MAE_DATGENFAC(NO_NOMMAEFAC, TX_DESMAEFAC, NO_CAMPOFAC1, NO_CAMPOFAC2, FE_REGCREACI, FL_REGINACTI)
VALUES('ESTINTFAC', 'Guarda todos los estados en ejecución de la interface', 'CO', 'Correcto', GETDATE(), '0');
INSERT INTO MAE_DATGENFAC(NO_NOMMAEFAC, TX_DESMAEFAC, NO_CAMPOFAC1, NO_CAMPOFAC2, FE_REGCREACI, FL_REGINACTI)
VALUES('ESTINTFAC', 'Guarda todos los estados en ejecución de la interface', 'EJ', 'Ejecutando', GETDATE(), '0');
INSERT INTO MAE_DATGENFAC(NO_NOMMAEFAC, TX_DESMAEFAC, NO_CAMPOFAC1, NO_CAMPOFAC2, FE_REGCREACI, FL_REGINACTI)
VALUES('ESTINTFAC', 'Guarda todos los estados en ejecución de la interface', 'EX', 'Excepción', GETDATE(), '0');
--
INSERT INTO MAE_EMIDOCELE VALUES('10710440153', '0000' ,'SQL', 'DESKTOP-U45U0IC\SQLEXPRESS', 'RSFACCAR', 'SA', 'A123456$', GETDATE(), NULL, '0')
GO
--CREACION DE PROCEDURES

CREATE PROCEDURE SPS_SEG_GETERRINF
AS  
SELECT  
    ERROR_NUMBER() AS NU_ERRNUMBER
    ,ERROR_SEVERITY() AS NO_ERRSERVER
    ,ERROR_STATE() AS NO_ERROSTATE
    ,ERROR_PROCEDURE() AS NO_ERRORPROC
    ,ERROR_LINE() AS NU_ERRORLINE
    ,ERROR_MESSAGE() AS TX_ERRORMESS;  
GO

CREATE PROCEDURE SPS_MAE_EMIDOCELE
AS
BEGIN
	SELECT
		NID_EMIDOCELE,
		NU_EMINUMRUC,
		CO_EMICODANE,
		NO_BASTIPBAS,
		NO_BASNOMSRV,
		NO_BASNOMBAS,
		NO_BASUSRBAS,
		NO_BASUSRPAS,
		FE_REGCREACI,
		FE_REGMODIFI,
		FL_REGINACTI
	FROM MAE_EMIDOCELE
	WHERE FL_REGINACTI = '0'
	ORDER BY FE_REGCREACI
END
GO
CREATE PROCEDURE SPS_TBL_DOCELECAB
AS
BEGIN
	SELECT
		NID_DOCELECAB,
		NU_DOCSERSUN,
		NU_DOCNUMSUN,
		FE_DOCFECEMI,
		HO_DOCHOREMI,
		CO_DOCTIPDOC,
		CO_DOCTIPMND,
		FE_DOCFECVEN,
		CO_EMITIPDOC,
		NU_EMINUMRUC,
		NO_EMINOMCOM,
		NO_EMIRAZSOC,
		NO_EMIDOMDIR,
		NO_EMIDOMURB,
		NO_EMIDOMPRV,
		CO_EMIDOMUBI,
		NO_EMIDOMDEP,
		NO_EMIDOMDIS,
		CO_EMIDOMPAI,
		FL_VENTAITIN,
		NO_ITNDIRCOM,
		NO_ITNURBANI,
		NO_ITNPROVIN,
		CO_ITNCODUBI,
		NO_ITNDEPART,
		NO_ITNDISTRI,
		CO_ITNCODPAI,
		FL_VENTAEXPO,
		CO_EXPCODPAI,
		CO_EMICODANE,
		CO_RECTIPDOC,
		NU_RECNUMDOC,
		NO_RECRAZSOC,
		CO_REMTIPDOC,
		NU_REMNUMDOC,
		FL_REFADIDOC,
		MT_TOTMONIMP,
		MT_TOTVENEXP,
		MT_TOTIMPEXP,
		CO_CODTRIEXP,
		MT_TOTVENINA,
		MT_TOTIMPINA,
		CO_CODTRIINA,
		MT_TOTVENEXO,
		MT_TOTIMPEXO,
		CO_CODTRIEXO,
		MT_TOTVENGRA,
		MT_TOTIMPGRA,
		CO_CODTRIGRA,
		MT_TOTVENGRV,
		MT_TOTIMPGRV,
		CO_CODTRIGRV,
		MT_ISCMONBAS,
		MT_TOTMONISC,
		FL_CARGODESC,
		CO_CODCARDES,
		PO_CARDESPRC,
		MT_MONCARDES,
		MT_CARDESBAS,
		MT_TOTMONDES,
		MT_TOTMONCAR,
		MT_TOTIMPORT,
		MT_TOTVALVEN,
		MT_TOTPREVEN,
		CO_ADILEYEND,
		TX_ADIDESLEY,
		CO_ADITIPOPE,
		FL_PERCEPCIO,
		NO_PERINCADE,
		CO_PERREASON,
		PO_PERPORAPL,
		MT_PERMONPER,
		MT_PERBASIMP,
		FL_ANTICIPOS,
		MT_TOTMONANT,
		CO_GUIARUBIG,
		NO_GUIARDIRE,
		NO_GUIARURBA,
		NO_GUIARPROV,
		NO_GUIARDEPA,
		NO_GUIARDIST,
		CO_GUIARPAIS,
		FL_DETRACCIO,
		CO_DTRCODBIE,
		NO_DTRCUEBAN,
		MT_DTRMONDTR,
		PO_DTRPRCDTR,
		CO_SUNESTENV,
		TX_SUNRESENV,
		FL_SUNDOCXML,
		XM_SUNDOCXML,
		FL_SUNDOCPDF,
		B6_SUNDOCPDF,
		FL_SUNDOCCDR,
		B6_SUNDOCCDR,
		--
		FE_REGCREACI,
		FE_REGMODIFI,
		FL_REGINACTI
	FROM TBL_DOCELECAB 
	WHERE FL_REGINACTI = '0'
	ORDER BY FE_REGCREACI
END
GO
CREATE PROCEDURE SPS_TBL_DOCELEDET
AS
BEGIN
	SELECT
		NID_DOCELEDET,
		NU_DETORDITM,
		CO_DETUNDMED,
		QT_DETCANITM,
		CO_DETCODPRO,
		CO_DETCOPRSU,
		CO_DETCODGS1,
		TX_DETDESITM,
		MT_DETVALUNI,
		MT_DETPREVEN,
		CO_DETCODPRE,
		MT_DETVALREF,
		CO_DETCOVARE,
		MT_DETTOTIMP,
		MT_AFEMONBAS,
		MT_AFEMONAFE,
		PO_AFEMONPRC,
		CO_AFEREASON,
		CO_AFECODTRI,
		MT_ISCMONBAS,
		MT_ISCMONAFE,
		PO_ISCMONPRC,
		CO_ISCTIPSIS,
		CO_ISCCODTRI,
		MT_DETVALVEN,
		NO_DETCARDES,
		CO_CARDESREA,
		DE_CARDESFAC,
		MT_CARDESMON,
		MT_CDEMONBAS,
		--
		FE_REGCREACI,
		FE_REGMODIFI,
		FL_REGINACTI	
	FROM TBL_DOCELEDET
	WHERE FL_REGINACTI = '0'
	ORDER BY FE_REGCREACI
END
GO

CREATE PROCEDURE SPS_TL_PROFACINT_BY_EMIDOCELE(
	@NID_EMIDOCELE INT,
	@CO_ESTPROINT VARCHAR(30),
	@CO_TIPPROFAC VARCHAR(30)
)
AS
BEGIN
	SELECT NID_EMIDOCELE, CO_ESTPROINT, CO_TIPPROFAC
	FROM TL_PROFACINT
	WHERE CO_ESTPROINT = @CO_ESTPROINT
	AND CO_TIPPROFAC = @CO_TIPPROFAC
	AND NID_EMIDOCELE = @NID_EMIDOCELE
	AND FL_REGINACTI = '0'
	ORDER BY FE_REGCREACI
END
GO

CREATE PROCEDURE SPI_TL_PROFACINT(
	@CO_TIPPROFAC VARCHAR(30), 
	@CO_ESTPROINT VARCHAR(30), 
	@NID_EMIDOCELE INT
)
AS
BEGIN
	DECLARE @NO_TRANSNAME VARCHAR(20);
	SELECT @NO_TRANSNAME = 'IPROFACINT'
	BEGIN TRANSACTION
	BEGIN TRY
		DECLARE @NO_TIPPROFAC VARCHAR(150),
				@NO_ESTPROINT VARCHAR(150)

		SELECT @NO_TIPPROFAC = TIPPROFAC.NO_CAMPOFAC2
		FROM MAE_DATGENFAC TIPPROFAC
		WHERE TIPPROFAC.NO_NOMMAEFAC = 'TIPPROINT'
		AND TIPPROFAC.NO_CAMPOFAC1 = @CO_TIPPROFAC
		AND TIPPROFAC.FL_REGINACTI = '0'

		SELECT @NO_ESTPROINT = ESTPROINT.NO_CAMPOFAC2
		FROM MAE_DATGENFAC ESTPROINT
		WHERE ESTPROINT.NO_NOMMAEFAC = 'ESTINTFAC'
		AND ESTPROINT.NO_CAMPOFAC1 = @CO_ESTPROINT
		AND ESTPROINT.FL_REGINACTI = '0'

		INSERT INTO TL_PROFACINT(CO_ESTPROINT, NO_ESTPROINT, CO_TIPPROFAC, NO_TIPPROFAC, FE_REGCREACI, NID_EMIDOCELE, FL_REGINACTI)
		SELECT @CO_ESTPROINT, @NO_ESTPROINT, @CO_TIPPROFAC, @NO_TIPPROFAC, GETDATE(), @NID_EMIDOCELE, '0'
		
		
		IF @@TRANCOUNT > 0
		BEGIN
			COMMIT TRANSACTION @NO_TRANSNAME;
		END
	END TRY
	BEGIN CATCH
		ROLLBACK TRANSACTION @NO_TRANSNAME;
		EXEC SPS_SEG_GETERRINF;
	END CATCH
END
GO