USE RSFACCAR
GO

ALTER DATABASE RSFACCAR
SET COMPATIBILITY_LEVEL = 130 -- For SQL Server 2016
GO

CREATE PROCEDURE SPS_FT0003FACC_BY_ESTDOCELE(
@TX_ESTDOCELE VARCHAR(150))
AS
BEGIN
	SELECT * FROM FT0003FACC WHERE F5_ESTADO_ENVIO IN(
		SELECT value  
		FROM STRING_SPLIT(@TX_ESTDOCELE, ',')  
		WHERE RTRIM(value) <> ''
	)
END
GO

CREATE PROCEDURE SPS_FT0003FACD_BY_FT0003FACC(
	@CO_DETALTIDO CHAR(2),
	@NU_DETSERSUN CHAR(4),
	@NU_DETNUMSUN CHAR(7)
)
AS
BEGIN
	SELECT * FROM FT0003FACD
	WHERE F6_CTD = @CO_DETALTIDO
	AND F6_CNUMSER = @NU_DETSERSUN
	AND F6_CNUMDOC = @NU_DETNUMSUN
END